[package]
name = "bevygame"
version = "0.1.0"
authors = ["Evgeny Papazyan <swordelf@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3" # make sure this is the latest version
